# Generated by Django 5.0.6 on 2024-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
    ]
