# Generated by Django 5.0.6 on 2024-05-18 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_categoria_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categoria",
            name="descripcion",
        ),
    ]
