# Generated by Django 5.0.6 on 2024-05-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_remove_categoria_descripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen_url",
        ),
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
        migrations.AlterField(
            model_name="producto",
            name="nombre",
            field=models.CharField(max_length=100),
        ),
    ]
