# Generated by Django 5.0.6 on 2024-05-19 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0004_remove_producto_imagen_url_producto_imagen_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="producto",
            name="imagen",
        ),
        migrations.CreateModel(
            name="ProductoImagen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagen", models.ImageField(upload_to="productos/")),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="imagenes",
                        to="catalogo.producto",
                    ),
                ),
            ],
        ),
    ]
