# Generated by Django 5.0.6 on 2024-05-24 13:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0005_remove_producto_imagen_productoimagen"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interes",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="interes",
            name="usuario",
        ),
        migrations.AddField(
            model_name="interes",
            name="email",
            field=models.EmailField(default="example@example.com", max_length=254),
        ),
        migrations.AddField(
            model_name="interes",
            name="fecha",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interes",
            name="nombre",
            field=models.CharField(default="Nombre Predeterminado", max_length=255),
        ),
        migrations.AddField(
            model_name="interes",
            name="producto_deseado",
            field=models.CharField(
                default="Producto Deseado Predeterminado", max_length=255
            ),
            preserve_default=False,
        ),
    ]
